// Generated by SwiftSemanticRuleCatalogGenerator.
// Do not edit manually.

public extension SwiftSemanticRuleSet {
    static var all: Self {
        get throws {
            try Self(
                rules: [
                    SwiftSemanticRules.API.ValidateMethod(),
                    SwiftSemanticRules.Enums.RedundantStringRawValue(),
                    SwiftSemanticRules.Formatting.ArgumentNesting(),
                    SwiftSemanticRules.Formatting.ClosingDelimiter(),
                    SwiftSemanticRules.Formatting.Indentation(),
                    SwiftSemanticRules.Formatting.VerticalArguments(),
                    SwiftSemanticRules.Source.NoEmoji(),
                    SwiftSemanticRules.Traps.ForceTry(),
                    SwiftSemanticRules.Traps.ForceUnwrap(),
                ]
            )
        }
    }
}
